import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).parent.parent

def get_mesonh_code_dir() -> str:
    return os.getenv("MESONH_CODE_DIR", str(BASE_DIR))

def get_mesonh_doc_dir() -> str:
    return os.getenv("MESONH_DOC_DIR", str(BASE_DIR))

# Derived paths
EXAMPLES_DIR = os.path.join(get_mesonh_code_dir(), "examples")
DOC_DIR = os.path.join(get_mesonh_doc_dir(), "docs/source/documentation/users_guide/executables_namelists/namelists")
EXECUTABLES_DIR = os.path.join(get_mesonh_doc_dir(), "docs/source/documentation/users_guide/executables_namelists")

def setup_wizard():
    """Interactive first-time setup wizard."""
    print("=" * 60)
    print("Meso-NH Namelist Editor - First Time Setup")
    print("=" * 60)
    print()
    
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        print(f".env file already exists at {env_file}")
        overwrite = input("Overwrite? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    print("\nPlease provide the paths to the Meso-NH repositories:")
    print()
    
    default_code = str(BASE_DIR)
    prompt_code = f"Path to Meso-NH CODE repo (contains 'examples/' folder) [{default_code}]: "
    mesonh_code_dir = input(prompt_code).strip()
    if not mesonh_code_dir:
        mesonh_code_dir = default_code
    
    examples_path = Path(mesonh_code_dir) / "examples"
    if not examples_path.exists():
        print(f"WARNING: {examples_path} does not exist!")
        proceed = input("Continue anyway? (y/N): ").strip().lower()
        if proceed != 'y':
            print("Setup cancelled.")
            return
    
    default_doc = str(BASE_DIR)
    prompt_doc = f"Path to Meso-NH DOC repo (contains 'docs/.../namelists/') [{default_doc}]: "
    mesonh_doc_dir = input(prompt_doc).strip()
    if not mesonh_doc_dir:
        mesonh_doc_dir = default_doc
    
    namelists_path = Path(mesonh_doc_dir) / "docs" / "source" / "documentation" / "users_guide" / "executables_namelists" / "namelists"
    if not namelists_path.exists():
        print(f"WARNING: {namelists_path} does not exist!")
        proceed = input("Continue anyway? (y/N): ").strip().lower()
        if proceed != 'y':
            print("Setup cancelled.")
            return
    
    env_content = f"""# Meso-NH Namelist Editor Configuration
# Generated by setup wizard

# Path to Meso-NH CODE repository (contains 'examples/' folder)
MESONH_CODE_DIR={mesonh_code_dir}

# Path to Meso-NH DOCUMENTATION repository (contains 'docs/.../namelists/')
MESONH_DOC_DIR={mesonh_doc_dir}
"""
    
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print()
    print(f"Configuration saved to {env_file}")
    print()
    print("You can now run the application with:")
    print("  streamlit run Applications.py")
    print()

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "setup":
        setup_wizard()
